// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query-7.sql

package sqlcrepo

import (
	"context"
)

const getOrderTotalByID = `-- name: GetOrderTotalByID :one
SELECT total FROM orders WHERE id = $1
`

// 7. No model file depedency example
func (q *Queries) GetOrderTotalByID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getOrderTotalByID, id)
	var total int32
	err := row.Scan(&total)
	return total, err
}
