// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query-4.sql

package sqlcrepo

import (
	"context"

	"github.com/berk-karaal/sqlc-gen-go-demo/development-testing/internal/business/entities"
)

const getOrderStatusAndTotalByID = `-- name: GetOrderStatusAndTotalByID :one
SELECT status, total FROM orders WHERE id = $1
`

type GetOrderStatusAndTotalByIDRow struct {
	Status entities.OrderStatus
	Total  int32
}

// 4. Returning a model file enum inside return struct example
func (q *Queries) GetOrderStatusAndTotalByID(ctx context.Context, id int32) (GetOrderStatusAndTotalByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderStatusAndTotalByID, id)
	var i GetOrderStatusAndTotalByIDRow
	err := row.Scan(&i.Status, &i.Total)
	return i, err
}
