// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query-6.sql

package sqlcrepo

import (
	"context"

	"github.com/berk-karaal/sqlc-gen-go-demo/development-testing/internal/business/entities"
)

const getOrderIDsUserIDAndStatus = `-- name: GetOrderIDsUserIDAndStatus :many
SELECT id FROM orders WHERE user_id = $1 AND status = $2
`

type GetOrderIDsUserIDAndStatusParams struct {
	UserID int32
	Status entities.OrderStatus
}

// 6. Get a model file enum inside argument struct example
func (q *Queries) GetOrderIDsUserIDAndStatus(ctx context.Context, arg GetOrderIDsUserIDAndStatusParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getOrderIDsUserIDAndStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
