// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcrepo

import (
	"context"

	"github.com/berk-karaal/sqlc-gen-go-demo/development-testing/internal/business/entities"
)

type Querier interface {
	// 10. Batch query return enum example
	BatchRetrieveOrderStatus(ctx context.Context, id []int32) *BatchRetrieveOrderStatusBatchResults
	// 11. Batch query return enum inside return struct example
	BatchRetrieveOrderStatusAndTotal(ctx context.Context, id []int32) *BatchRetrieveOrderStatusAndTotalBatchResults
	// 9. Batch query return model struct example
	BatchRetrieveOrders(ctx context.Context, id []int32) *BatchRetrieveOrdersBatchResults
	// 8. Batch query enum inside argument struct example
	BatchUpdateOrderStatus(ctx context.Context, arg []BatchUpdateOrderStatusParams) *BatchUpdateOrderStatusBatchResults
	// 5. Get a model file enum as argument example
	GetOrderIDsByStatus(ctx context.Context, status entities.OrderStatus) ([]int32, error)
	// 6. Get a model file enum inside argument struct example
	GetOrderIDsUserIDAndStatus(ctx context.Context, arg GetOrderIDsUserIDAndStatusParams) ([]int32, error)
	// 4. Returning a model file enum inside return struct example
	GetOrderStatusAndTotalByID(ctx context.Context, id int32) (GetOrderStatusAndTotalByIDRow, error)
	// 3. Returning a model file enum example
	GetOrderStatusByID(ctx context.Context, id int32) (entities.OrderStatus, error)
	// 7. No model file depedency example
	GetOrderTotalByID(ctx context.Context, id int32) (int32, error)
	// 2. Returning single model struct example
	GetUserByID(ctx context.Context, id int32) (entities.User, error)
	// 1. Returning list of model struct example
	ListUsers(ctx context.Context) ([]entities.User, error)
}

var _ Querier = (*Queries)(nil)
