// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query-3.sql

package sqlcrepo

import (
	"context"

	"github.com/berk-karaal/sqlc-gen-go-demo/development-testing/internal/business/entities"
)

const getOrderStatusByID = `-- name: GetOrderStatusByID :one
SELECT status FROM orders WHERE id = $1
`

// 3. Returning a model file enum example
func (q *Queries) GetOrderStatusByID(ctx context.Context, id int32) (entities.OrderStatus, error) {
	row := q.db.QueryRow(ctx, getOrderStatusByID, id)
	var status entities.OrderStatus
	err := row.Scan(&status)
	return status, err
}
