// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query-12.sql

package sqlcrepo

import (
	"context"

	"github.com/berk-karaal/sqlc-gen-go-demo/development-testing/internal/business/entities"
)

const getOrderWithUserByOrderId = `-- name: GetOrderWithUserByOrderId :one
SELECT orders.id, orders.user_id, orders.total, orders.status, users.id, users.email, users.full_name, users.is_active, users.created_at, users.updated_at
FROM orders
LEFT OUTER JOIN users ON orders.user_id = users.id
WHERE orders.id = $1
`

type GetOrderWithUserByOrderIdRow struct {
	Order entities.Order
	User  entities.User
}

// 12. Struct embedding
func (q *Queries) GetOrderWithUserByOrderId(ctx context.Context, id int32) (GetOrderWithUserByOrderIdRow, error) {
	row := q.db.QueryRow(ctx, getOrderWithUserByOrderId, id)
	var i GetOrderWithUserByOrderIdRow
	err := row.Scan(
		&i.Order.ID,
		&i.Order.UserID,
		&i.Order.Total,
		&i.Order.Status,
		&i.User.ID,
		&i.User.Email,
		&i.User.FullName,
		&i.User.IsActive,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}
