// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query-1.sql

package sqlcrepo

import (
	"context"

	"github.com/berk-karaal/sqlc-gen-go-demo/development-testing/internal/business/entities"
)

const listUsers = `-- name: ListUsers :many
SELECT id, email, full_name, is_active, created_at, updated_at FROM users
`

// 1. Returning list of model struct example
func (q *Queries) ListUsers(ctx context.Context) ([]entities.User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []entities.User
	for rows.Next() {
		var i entities.User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
