// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query-2.sql

package sqlcrepo

import (
	"context"

	"github.com/berk-karaal/sqlc-gen-go-demo/development-testing/internal/business/entities"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, full_name, is_active, created_at, updated_at FROM users WHERE id = $1
`

// 2. Returning single model struct example
func (q *Queries) GetUserByID(ctx context.Context, id int32) (entities.User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i entities.User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
